---
- name: Install k3s on the application server
  hosts: k8s
  become: true
  gather_facts: true

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Install k3s without Traefik
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_EXEC: "server --disable traefik"

    - name: Enable and start k3s
      ansible.builtin.systemd:
        name: k3s
        enabled: true
        state: started
        daemon_reload: true

    - name: Create kubectl command
      ansible.builtin.file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
        force: true

    - name: Check Kubernetes node status
      ansible.builtin.command:
        cmd: kubectl get nodes
      register: kubernetes_nodes
      changed_when: false

    - name: Display Kubernetes node status
      ansible.builtin.debug:
        var: kubernetes_nodes.stdout_lines
